from mteb.models.model_meta import ModelMeta, ScoringFunction
from mteb.models.sentence_transformer_wrapper import SentenceTransformerEncoderWrapper

_DSE_BERT_CITATION = """
@misc{zhou2022learningdialoguerepresentationsconsecutive,
    title={Learning Dialogue Representations from Consecutive Utterances}, 
    author={Zhihan Zhou and Dejiao Zhang and Wei Xiao and Nicholas Dingwall and Xiaofei Ma and Andrew O. Arnold and Bing Xiang},
    year={2022},
    eprint={2205.13568},
    archivePrefix={arXiv},
    primaryClass={cs.CL},
    url={https://arxiv.org/abs/2205.13568}, 
}
"""

dse_bert_base = ModelMeta(
    loader=SentenceTransformerEncoderWrapper,
    loader_kwargs={},
    name="aws-ai/dse-bert-base",
    revision="918ad931256ade24add8b1840a710e9e96bc9b40",
    release_date="2022-07-10",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=23440896,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers"],
    reference="https://huggingface.co/aws-ai/dse-bert-base",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_DSE_BERT_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

dse_roberta_large = ModelMeta(
    loader=SentenceTransformerEncoderWrapper,
    loader_kwargs={},
    name="aws-ai/dse-roberta-large",
    revision="1a3a00fb5a1e4a552f1c75a2a537eff09bea777c",
    release_date="2022-07-11",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=51471360,
    memory_usage_mb=None,
    max_tokens=514,
    embed_dim=1024,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers"],
    reference="https://huggingface.co/aws-ai/dse-roberta-large",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_DSE_BERT_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

dse_roberta_base = ModelMeta(
    loader=SentenceTransformerEncoderWrapper,
    loader_kwargs={},
    name="aws-ai/dse-roberta-base",
    revision="bdb4005e439cd26d3736a7a45f56737d7f7cd47c",
    release_date="2022-07-11",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=38603520,
    memory_usage_mb=None,
    max_tokens=514,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers"],
    reference="https://huggingface.co/aws-ai/dse-roberta-base",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_DSE_BERT_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

dse_bert_large = ModelMeta(
    loader=SentenceTransformerEncoderWrapper,
    loader_kwargs={},
    name="aws-ai/dse-bert-large",
    revision="7100d49b06f74ea00f6acebe4f74d342ec9b30d2",
    release_date="2022-07-10",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=31254528,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=1024,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers"],
    reference="https://huggingface.co/aws-ai/dse-bert-large",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_DSE_BERT_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)
