from sentence_transformers import SentenceTransformer
from sentence_transformers.models import Pooling, Transformer

from mteb.models.model_meta import ModelMeta, ScoringFunction
from mteb.models.sentence_transformer_wrapper import SentenceTransformerEncoderWrapper


class SimCSEWrapper(SentenceTransformerEncoderWrapper):
    def __init__(
        self,
        model: str,
        revision: str | None = None,
        device: str | None = None,
        *,
        embed_dim: int | None = None,
        **kwargs,
    ) -> None:
        shared_kwargs = {
            "revision": revision,
        }
        transformer_model = Transformer(
            model,
            model_args=shared_kwargs,
            tokenizer_args=shared_kwargs,
            config_args=shared_kwargs,
        )
        pooling_model = Pooling(transformer_model.get_word_embedding_dimension(), "cls")
        modules = [transformer_model, pooling_model]
        model = SentenceTransformer(
            modules=modules,
            revision=revision,
            device=device,
            truncate_dim=embed_dim,
            **kwargs,
        )
        super().__init__(model, revision, device=device, **kwargs)


_SIM_CSE_CITATION = """
@misc{gao2022simcsesimplecontrastivelearning,
    title={SimCSE: Simple Contrastive Learning of Sentence Embeddings}, 
    author={Tianyu Gao and Xingcheng Yao and Danqi Chen},
    year={2022},
    eprint={2104.08821},
    archivePrefix={arXiv},
    primaryClass={cs.CL},
    url={https://arxiv.org/abs/2104.08821}, 
}"""

sup_simcse_bert_base_uncased = ModelMeta(
    loader=SimCSEWrapper,
    name="princeton-nlp/sup-simcse-bert-base-uncased",
    revision="2d82fab19ac3a73a20dd20333d27eb8a52d6e97f",
    release_date="2021-04-21",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=23440896,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "JAX", "Transformers"],
    reference="https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_SIM_CSE_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)
unsup_simcse_roberta_base = ModelMeta(
    loader=SimCSEWrapper,
    loader_kwargs={},
    name="princeton-nlp/unsup-simcse-roberta-base",
    revision="db28710348cf9f33a2be25c505f98f0fbbbfe768",
    release_date="2021-05-12",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=38603520,
    memory_usage_mb=None,
    max_tokens=514,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "JAX", "Transformers"],
    reference="https://huggingface.co/princeton-nlp/unsup-simcse-roberta-base",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_SIM_CSE_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

unsup_simcse_bert_large_uncased = ModelMeta(
    loader=SimCSEWrapper,
    loader_kwargs={},
    name="princeton-nlp/unsup-simcse-bert-large-uncased",
    revision="e0dd30b6cbdccd205ff17967417c90faa49992d8",
    release_date="2021-05-12",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=31254528,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=1024,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "JAX", "Transformers"],
    reference="https://huggingface.co/princeton-nlp/unsup-simcse-bert-large-uncased",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_SIM_CSE_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

unsup_simcse_roberta_large = ModelMeta(
    loader=SimCSEWrapper,
    loader_kwargs={},
    name="princeton-nlp/unsup-simcse-roberta-large",
    revision="d3f863b476c59b0673264042f159cea15842e265",
    release_date="2021-05-12",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=51471360,
    memory_usage_mb=None,
    max_tokens=514,
    embed_dim=1024,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "JAX", "Transformers"],
    reference="https://huggingface.co/princeton-nlp/unsup-simcse-roberta-large",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_SIM_CSE_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

sup_simcse_bert_large_uncased = ModelMeta(
    loader=SimCSEWrapper,
    loader_kwargs={},
    name="princeton-nlp/sup-simcse-bert-large-uncased",
    revision="fee654985cba2109906c28abb1967a2f4d4e316f",
    release_date="2021-04-21",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=31254528,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=1024,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "JAX", "Transformers"],
    reference="https://huggingface.co/princeton-nlp/sup-simcse-bert-large-uncased",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_SIM_CSE_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

sup_simcse_roberta_base = ModelMeta(
    loader=SimCSEWrapper,
    loader_kwargs={},
    name="princeton-nlp/sup-simcse-roberta-base",
    revision="4bf73c6b5df517f74188c5e9ec159b2208c89c08",
    release_date="2021-04-21",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=38603520,
    memory_usage_mb=None,
    max_tokens=514,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "JAX", "Transformers"],
    reference="https://huggingface.co/princeton-nlp/sup-simcse-roberta-base",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_SIM_CSE_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

sup_simcse_roberta_large = ModelMeta(
    loader=SimCSEWrapper,
    loader_kwargs={},
    name="princeton-nlp/sup-simcse-roberta-large",
    revision="96d164d9950b72f4ce179cb1eb3414de0910953f",
    release_date="2021-04-21",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=51471360,
    memory_usage_mb=None,
    max_tokens=514,
    embed_dim=1024,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "JAX", "Transformers"],
    reference="https://huggingface.co/princeton-nlp/sup-simcse-roberta-large",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation=_SIM_CSE_CITATION,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

tod_bert_mlm = ModelMeta(
    loader=SimCSEWrapper,
    loader_kwargs={},
    name="TODBERT/TOD-BERT-MLM-V1",
    revision="34178a6c57ace7efbf9423aae288804eb163f326",
    release_date="2020-07-11",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=23442432,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "TensorFlow", "JAX", "Transformers"],
    reference="https://huggingface.co/TODBERT/TOD-BERT-MLM-V1",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation="""
@misc{wu2020todbertpretrainednaturallanguage,
    title={TOD-BERT: Pre-trained Natural Language Understanding for Task-Oriented Dialogue}, 
    author={Chien-Sheng Wu and Steven Hoi and Richard Socher and Caiming Xiong},
    year={2020},
    eprint={2004.06871},
    archivePrefix={arXiv},
    primaryClass={cs.CL},
    url={https://arxiv.org/abs/2004.06871}, 
}""",
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

futuretod = ModelMeta(
    loader=SimCSEWrapper,
    loader_kwargs={},
    name="AndrewZeng/futuretod-base-v1.0",
    revision="293eb5f4dc88bcc340135656680d9c0ef2b67d39",
    release_date="2023-07-05",
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=23442432,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers"],
    reference="https://huggingface.co/AndrewZeng/futuretod-base-v1.0",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["dense"],
    citation="""
@misc{zeng2023futuretodteachingfutureknowledge,
    title={FutureTOD: Teaching Future Knowledge to Pre-trained Language Model for Task-Oriented Dialogue}, 
    author={Weihao Zeng and Keqing He and Yejie Wang and Chen Zeng and Jingang Wang and Yunsen Xian and Weiran Xu},
    year={2023},
    eprint={2306.10315},
    archivePrefix={arXiv},
    primaryClass={cs.CL},
    url={https://arxiv.org/abs/2306.10315}, 
}""",
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

dse_bert_base = ModelMeta(
    loader=SentenceTransformerEncoderWrapper,
    loader_kwargs={},
    name='aws-ai/dse-bert-base',
    revision='918ad931256ade24add8b1840a710e9e96bc9b40',
    release_date='2022-07-10',
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=23440896,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=['PyTorch', 'Transformers'],
    reference='https://huggingface.co/aws-ai/dse-bert-base',
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=['text'],
    model_type=['dense'],
    citation=None,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

dse_roberta_large = ModelMeta(
    loader=SentenceTransformerEncoderWrapper,
    loader_kwargs={},
    name='aws-ai/dse-roberta-large',
    revision='1a3a00fb5a1e4a552f1c75a2a537eff09bea777c',
    release_date='2022-07-11',
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=51471360,
    memory_usage_mb=None,
    max_tokens=514,
    embed_dim=1024,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=['PyTorch', 'Transformers'],
    reference='https://huggingface.co/aws-ai/dse-roberta-large',
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=['text'],
    model_type=['dense'],
    citation=None,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

dse_roberta_base = ModelMeta(
    loader=SentenceTransformerEncoderWrapper,
    loader_kwargs={},
    name='aws-ai/dse-roberta-base',
    revision='bdb4005e439cd26d3736a7a45f56737d7f7cd47c',
    release_date='2022-07-11',
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=38603520,
    memory_usage_mb=None,
    max_tokens=514,
    embed_dim=768,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=['PyTorch', 'Transformers'],
    reference='https://huggingface.co/aws-ai/dse-roberta-base',
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=['text'],
    model_type=['dense'],
    citation=None,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)

dse_bert_large = ModelMeta(
    loader=SentenceTransformerEncoderWrapper,
    loader_kwargs={},
    name='aws-ai/dse-bert-large',
    revision='7100d49b06f74ea00f6acebe4f74d342ec9b30d2',
    release_date='2022-07-10',
    languages=None,
    n_parameters=None,
    n_active_parameters_override=None,
    n_embedding_parameters=31254528,
    memory_usage_mb=None,
    max_tokens=512,
    embed_dim=1024,
    license=None,
    open_weights=None,
    public_training_code=None,
    public_training_data=None,
    framework=['PyTorch', 'Transformers'],
    reference='https://huggingface.co/aws-ai/dse-bert-large',
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=None,
    training_datasets=None,
    adapted_from=None,
    superseded_by=None,
    modalities=['text'],
    model_type=['dense'],
    citation=None,
    contacts=None,
    output_dtypes=None,
    extra_requirements_groups=None,
)