"""Generate a consolidated BibTeX file for all DialogMTEB tasks and run.py models.

Sources:
  - Task citations: task.metadata.bibtex_citation
  - Model citations: mteb.get_model_meta(name).citation

Deduplication is done by BibTeX key. Missing citations are written as
placeholder entries and listed in a warnings section at the top.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from scripts.dialogmteb._common import OUT_DIR, load_unique_tasks, RUN_MODELS

import mteb



# -----------------------------------------------------------------------
# BibTeX utilities
# -----------------------------------------------------------------------

_KEY_RE = re.compile(r"@\w+\{([^,\s]+)\s*,", re.MULTILINE)


def extract_key(bibtex: str) -> str | None:
    m = _KEY_RE.search(bibtex)
    return m.group(1).strip() if m else None


def normalize_bibtex(bibtex: str) -> str:
    """Strip leading/trailing whitespace from a bibtex entry."""
    return bibtex.strip()


def collect_entries(
    raw_bibtex: str,
) -> list[tuple[str, str]]:
    """Split a string that may contain multiple @-entries into (key, entry) pairs."""
    entries = []
    for chunk in re.split(r"\n(?=@)", raw_bibtex.strip()):
        chunk = chunk.strip()
        if not chunk:
            continue
        key = extract_key(chunk)
        if key:
            entries.append((key, chunk))
    return entries


# -----------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------


def main():
    # Collect all bibtex: key → entry string (first-seen wins)
    seen: dict[str, str] = {}  # key → bibtex entry
    source_map: dict[str, list[str]] = {}  # key → [model/task names]
    warnings: list[str] = []

    # ── Tasks ────────────────────────────────────────────────────────────
    tasks = load_unique_tasks()
    print(f"Processing {len(tasks)} tasks...")
    for task in tasks:
        bibtex = task.metadata.bibtex_citation or ""
        if not bibtex.strip():
            warnings.append(f"[TASK] No citation: {task.metadata.name}")
            continue
        for key, entry in collect_entries(bibtex):
            source_map.setdefault(key, []).append(f"task:{task.metadata.name}")
            if key not in seen:
                seen[key] = normalize_bibtex(entry)

    # ── Models ───────────────────────────────────────────────────────────
    print(f"Processing {len(RUN_MODELS)} models...")

    for model in RUN_MODELS:
        meta = mteb.get_model_meta(model)
        bibtex = str(meta.citation).strip()

        if not bibtex:
            warnings.append(f"[MODEL] No citation: {model}")
            continue

        for key, entry in collect_entries(bibtex):
            source_map.setdefault(key, []).append(f"model:{model}")
            if key not in seen:
                seen[key] = normalize_bibtex(entry)

    # ── Write .bib file ──────────────────────────────────────────────────
    out = OUT_DIR / "dialogmteb_references.bib"

    header_lines = [
        "% DialogMTEB References",
        "% Auto-generated by generate_references_bib.py",
        f"% Tasks: {len(tasks)}  |  Models: {len(RUN_MODELS)}",
        f"% Total unique entries: {len(seen)}",
        "%",
    ]
    if warnings:
        header_lines.append("% WARNINGS — entries with no citation found:")
        for w in warnings:
            header_lines.append(f"%   {w}")
    header_lines.append("")

    # Group entries: task citations first, then model citations
    task_keys = []
    model_keys = []
    other_keys = []
    for key in seen:
        sources = source_map.get(key, [])
        has_task = any(s.startswith("task:") for s in sources)
        has_model = any(s.startswith("model:") for s in sources)
        if has_task and not has_model:
            task_keys.append(key)
        elif has_model and not has_task:
            model_keys.append(key)
        else:
            other_keys.append(key)

    sections = []
    if task_keys:
        sections.append(
            (
                "% ── Task Citations ──────────────────────────────────────────────",
                sorted(task_keys),
            )
        )
    if model_keys:
        sections.append(
            (
                "% ── Model Citations ─────────────────────────────────────────────",
                sorted(model_keys),
            )
        )
    if other_keys:
        sections.append(
            (
                "% ── Shared Citations ────────────────────────────────────────────",
                sorted(other_keys),
            )
        )

    body_lines = []
    for section_header, keys in sections:
        body_lines.append(section_header)
        body_lines.append("")
        for key in keys:
            body_lines.append(seen[key])
            body_lines.append("")

    content = "\n".join(header_lines) + "\n" + "\n".join(body_lines)
    out.write_text(content)

    # ── Summary ───────────────────────────────────────────────────────────
    print(f"\nBibTeX file written to {out}")
    print(f"  Task-only entries : {len(task_keys)}")
    print(f"  Model-only entries: {len(model_keys)}")
    print(f"  Shared entries    : {len(other_keys)}")
    print(f"  Total unique keys : {len(seen)}")
    if warnings:
        print(f"\nWarnings ({len(warnings)}):")
        for w in warnings:
            print(f"  {w}")


if __name__ == "__main__":
    main()
